version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  web:
    build: .
    env_file:
      - .env

    volumes:
      - .:/usr/src/app
    command: gunicorn --bind :8000 --workers 3 blog.wsgi
    ports:
      - 8000:8000
    depends_on:
      - "db"
